export const getSelectedResident = state => state.residents.selectedResident
export const getResidentsList = state => state.data.residents
export const getHomeDocumentsList = state => state.data['home-documents']
export const getDocumentsList = state => state.data.documents
export const getSelectedUser = state => state.users.selectedUser
export const getUsersList = state => state.data.carers
export const getHandoversList = state => state.data.handovers
export const getCurrentHandover = state => state.handovers.current
export const getLogCategories = state => state.data['log-categories']
export const getLogCategoryItems = state => state.data['log-category-items']