export const SET_FORM_FIELD = 'app/Modal/SET_FORM_FIELD';
export const CLEAR_FORM_FIELD = 'app/Modal/CLEAR_FORM_FIELD';
export const CLEAR_ALL_FORM_FIELDS = 'app/Modal/CLEAR_ALL_FORM_FIELDS';
export const SUBMIT_FORM = 'app/Modal/SUBMIT_FORM';
export const SUBMIT_SUCCESS = 'app/Modal/SUBMIT_SUCCESS';
export const SUBMIT_ERROR = 'app/Modal/SUBMIT_ERROR';

export const SET_RECURRENCE_TYPE = 'app/Modal/SET_RECURRENCE_TYPE';
export const TOGGLE_RECURRENCE_OPTION = 'app/Modal/TOGGLE_RECURRENCE_OPTION';
export const TOGGLE_CREATE_TODO_MODAL = 'app/Modal/TOGGLE_CREATE_TODO_MODAL';
// export const UPDATE_RECURRENCE_OPTIONS = 'app/Modal/UPDATE_RECURRENCE_OPTIONS';